[text]WEBSITETITLE=Javascript Wiki[/text]
<header>
<title>[WEBSITETITLE] - [PAGETITLE]</title>
<audio autoplay loop>
    <source src="[PATHVAR]audio/bgmusic.mp3" type="audio/mpeg">
    Your browser does not support the audio element.
</audio>
<style>
[include file=[CSSVAR]style.css]
</style>
<div class="header">
Javascript Wiki<br>
</div>
[showif [debugVAR]=1]Dev stuff is showing[/showif] 
</header>



