
<html>
<head>
  <title><?php echo $WEBSITETITLE; ?> - <?php echo $PAGETITLE; ?></title>
  <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1">
  <link rel="stylesheet" href="<?php echo $cssVAR; ?>style.css">
</head>

<body bgcolor="#FFFFFF" text="#00FFFF" link="#B026FF" vlink="#800080" alink="#FF0000">

<center>
  <table width="100%" bgcolor="#000000" border="0" cellspacing="0" cellpadding="20">
    <tr>
      <td align="center">
        <font size="6" color="#FFFF00"><b><?php echo $WEBSITETITLE; ?></b></font>
        <?php if ($debugVAR == 1) { echo '<br><font size="2" color="#FF0000"><b>DEBUG ON</b></font>'; } ?>
      </td>
    </tr>
  </table>
</center>
