[showif [thisurl]^25admin25]
<div class="navbar">
  <a class="[showif [thisurl]=[adminVAR]index.html]activenav[/showif]" href="[adminVAR]index.html">Admin</a>[!]
  <a class="[showif [thisurl]=[adminVAR]contacts/index.html]activenav[/showif]" href="[adminVAR]contacts/index.html">Contacts</a>
  <a class="[showif [thisurl]=[adminVAR]country/index.html]activenav[/showif]" href="[adminVAR]country/index.html">Country</a>
  <a class="[showif [thisurl]=[adminVAR]state/index.html]activenav[/showif]" href="[adminVAR]state/index.html">State</a>
  <a class="[showif [thisurl]=[pathVAR]about_us/index.html]activenav[/showif]" href="[pathVAR]about_us/index.html">About Us</a>
  <a class="[showif [thisurl]=[pathVAR]blog/index.html]activenav[/showif]" href="[pathVAR]blog/index.html">Blog</a>
  <a class="[showif [thisurl]=[pathVAR]contact/index.html]activenav[/showif]" href="[pathVAR]contact/index.html">Contact</a>[/!][!]

  
  
  
<div class="dropdown">
<button class="dropbtn">Login 
<i class="fa fa-caret-down"></i>
</button>
<div class="dropdown-content">
<a class= "[showif [thisurl]=[pathVAR]/index.html]activenav_dropdown[/showif]" href="[pathVAR]/index.html">test</a>
</div>
</div>[/!]
</div>
[/showif]