<div class="nav">
  <a class="[showif [thisurl]=[apathVAR]index.html]activenav[/showif]" href="[apathVAR]index.html">Homepage</a>
  <a class="[showif [thisurl]=[apathVAR]login.html]activenav[/showif]" href="[apathVAR]login.html">Login</a>
    <a class="[showif [thisurl]=[apathVAR]settings.html]activenav[/showif]" href="[apathVAR]settings.html">Settings</a>
[SHOWIF [getcookie name=Student]=2594]
        <a class="[showif [thisurl]=[dpathVAR]HMadminHM/words/index.html]activenav[/showif]" href="[dpathVAR]HMadminHM/words/index.html">Words Admin</a>
    <a class="[showif [thisurl]=[dpathVAR]HMadminHM/members/index.html]activenav[/showif]" href="[dpathVAR]HMadminHM/members/index.html">Members Admin</a>
[/SHOWIF]
[SHOWIF [getcookie name=Student]=2559]
        <a class="[showif [thisurl]=[dpathVAR]HMadminHM/index.html]activenav[/showif]" href="[dpathVAR]HMadminHM/words/index.html">Words Admin</a>
    <a class="[showif [thisurl]=[dpathVAR]HMadminHM/members/index.html]activenav[/showif]" href="[dpathVAR]HMadminHM/members/index.html">Members Admin</a>
[/SHOWIF] 
  
  
[!]<div class="dropdown">
	<button class="dropbtn">Characters 
	<i class="fa fa-caret-down"></i>
	</button>
	<div class="dropdown-content">
	<a class= "[showif [thisurl]=[pathVAR]characters/character_alice_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_alice_md/index.html">Alice</a>
	<a class= "[showif [thisurl]=[pathVAR]characters/character_amda_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_amda_md/index.html">Amda</a>
	<a class= "[showif [thisurl]=[pathVAR]characters/character_cyn_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_cyn_md/index.html">Cyn</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_j_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_j_md/index.html">J</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_khan_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_khan_md/index.html">Khan</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_n_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_n_md/index.html">N</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_uzi_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_uzi_md/index.html">Uzi</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_v_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_v_md/index.html">V</a>
	</div>
</div>[/!]
</div>