<div class="navbar">
  <a class="[showif [thisurl]=[pathVAR]index.html]activenav[/showif]" href="[pathVAR]index.html">Homepage</a>
  <a class="[showif [thisurl]=[pathVAR]about_author/index.html]activenav[/showif]" href="[pathVAR]about_author/index.html">About Author</a>
  <a class="[showif [thisurl]=[pathVAR]about_website/index.html]activenav[/showif]" href="[pathVAR]about_website/index.html">About Website</a>
  <a class="[showif [thisurl]=[pathVAR]contact/index.html]activenav[/showif]" href="[pathVAR]contact/index.html">Contact</a>
  <a class="[showif [thisurl]=[pathVAR]gallery/index.html]activenav[/showif]" href="[pathVAR]gallery/index.html">Gallery</a>

  
  
  
<div class="dropdown">
	<button class="dropbtn">Characters 
	<i class="fa fa-caret-down"></i>
	</button>
	<div class="dropdown-content">
	<a class= "[showif [thisurl]=[pathVAR]characters/character_alice_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_alice_md/index.html">Alice</a>
	<a class= "[showif [thisurl]=[pathVAR]characters/character_amda_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_amda_md/index.html">Amda</a>
	<a class= "[showif [thisurl]=[pathVAR]characters/character_cyn_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_cyn_md/index.html">Cyn</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_j_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_j_md/index.html">J</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_khan_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_khan_md/index.html">Khan</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_n_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_n_md/index.html">N</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_uzi_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_uzi_md/index.html">Uzi</a>
	<a class="[showif [thisurl]=[pathVAR]characters/character_v_md/index.html]activenav_dropdown[/showif]" href="[pathVAR]characters/character_v_md/index.html">V</a>
	</div>
</div>
</div>