
<center>
  <table width="100%" bgcolor="#000000" border="0" cellspacing="0" cellpadding="10">
    <tr>
      <td align="center">
        <font size="3" color="#FFFF00">
          &copy; A.t.A. Tech Wiki, <?php echo date("l, F d, Y"); ?> - <?php echo date("g:i A"); ?>
        </font>
      </td>
    </tr>
  </table>
</center>

<?php if ($debugVAR == 1) include $incVAR . 'debug.inc'; ?>
</body>
</html>
